version: "3"

services:
  invoice:
    build: .
    image: yoksar/invoice-service
    environment: 
      DATABASE_URL: jdbc:mysql://192.168.178.24:9040/projectdb
      DATABASE_USER: mysql
      DATABASE_PASS: mysql
    ports:
      - 9000:8080