version: "2"

services:
  wildfly:
    container_name: "Wildfly"
    build: .
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=admin
      - DB_NAME=testdb
      - DB_USER=mysql
      - DB_PASS=mysql
      - DB_URI=db:3306
    volumes:
      - ./resources/:/media/resources/         #host resources like images
    command: "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug *:8787"
    depends_on:
      - db
    ports:
      - "8080:8080"     # application
      - "9990:9990"     # admin console
      - "8787:8787"     # debug   --debug *:8787

  db:
    container_name: "Wildfly_Database"
    image: "mysql:latest"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_VERSION=8.0.15
    volumes:
      - ./workdir/db/init/:/docker-entrypoint-initdb.d/ # init database
      - ./workdir/db/data/:/var/lib/mysql/              # data storage
    ports:
      - "3306:3306"     #Default
    
networks:
    default:
        driver: bridge